services:
  - type: web
    name: esubu-sacco-frontend
    env: static
    rootDir: ./
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: REACT_APP_API_URL
        value: "https://esubu-sacco-backend.onrender.com"
      - key: CI
        value: "false"
      - key: GENERATE_SOURCEMAP
        value: "false"
